import { StyleSheet } from "@react-pdf/renderer";

export const sharedStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1a1a1a",
    padding: 40,
    backgroundColor: "#ffffff",
  },
  headerBar: { height: 6, borderRadius: 2, marginBottom: 20 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  logo: { width: 60, height: 60, objectFit: "contain" },
  businessInfo: { alignItems: "flex-end" },
  businessName: { fontSize: 16, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  businessDetail: { fontSize: 9, color: "#555555", marginBottom: 1 },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingBottom: 12,
    borderBottom: "1 solid #e5e7eb",
  },
  documentTitle: { fontSize: 22, fontFamily: "Helvetica-Bold", color: "#1a1a1a" },
  documentMeta: { alignItems: "flex-end" },
  metaLabel: { fontSize: 8, color: "#999999", textTransform: "uppercase", marginBottom: 1 },
  metaValue: { fontSize: 10, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  billToRow: { flexDirection: "row", marginBottom: 20 },
  billToBox: {
    flex: 1,
    backgroundColor: "#f9fafb",
    padding: 12,
    borderRadius: 4,
    marginRight: 10,
  },
  billToLabel: {
    fontSize: 8,
    color: "#999999",
    textTransform: "uppercase",
    marginBottom: 6,
    fontFamily: "Helvetica-Bold",
  },
  billToName: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  billToDetail: { fontSize: 9, color: "#555555", marginBottom: 1 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    padding: "6 8",
    borderRadius: 3,
    marginBottom: 2,
  },
  tableHeaderText: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#6b7280",
    textTransform: "uppercase",
  },
  tableRow: { flexDirection: "row", padding: "7 8", borderBottom: "1 solid #f3f4f6" },
  tableRowAlt: {
    flexDirection: "row",
    padding: "7 8",
    backgroundColor: "#fafafa",
    borderBottom: "1 solid #f3f4f6",
  },
  colDescription: { flex: 4 },
  colQty: { flex: 1, textAlign: "right" },
  colUnit: { flex: 1, textAlign: "center" },
  colPrice: { flex: 1.5, textAlign: "right" },
  colGst: { flex: 0.8, textAlign: "center" },
  colTotal: { flex: 1.5, textAlign: "right" },
  cellText: { fontSize: 9, color: "#374151" },
  cellBold: { fontSize: 9, fontFamily: "Helvetica-Bold" },
  totalsSection: { alignItems: "flex-end", marginTop: 12, marginBottom: 20 },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginBottom: 3, width: 200 },
  totalLabel: { flex: 1, fontSize: 9, color: "#6b7280", textAlign: "right", paddingRight: 12 },
  totalValue: { width: 80, fontSize: 9, textAlign: "right" },
  grandTotalRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    width: 200,
    paddingTop: 6,
    borderTop: "1.5 solid #e5e7eb",
    marginTop: 4,
  },
  grandTotalLabel: {
    flex: 1,
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
    paddingRight: 12,
  },
  grandTotalValue: { width: 80, fontSize: 11, fontFamily: "Helvetica-Bold", textAlign: "right" },
  notesSection: { backgroundColor: "#f9fafb", padding: 12, borderRadius: 4, marginBottom: 20 },
  notesLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#6b7280",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  notesText: { fontSize: 9, color: "#374151", lineHeight: 1.5 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: "1 solid #e5e7eb",
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: { fontSize: 8, color: "#9ca3af" },
});
